import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";

test("my work, checklist completion, recurring next occurrence and project overview", async ({ page, request }, info) => {
  const email = `execution-${randomUUID()}@example.com`, password = "ExecutionValidation!42";
  expect((await request.post("/auth/register", { data: { email, password, name: "실행 검증" } })).status()).toBe(201);
  const token = (await (await request.post("/auth/login", { form: { username: email, password } })).json()).access_token;
  const headers = { Authorization: `Bearer ${token}` };
  const me = await (await request.get("/users/me", { headers })).json();
  const project = await (await request.post("/projects", { headers, data: { name: "실행 관리 프로젝트" } })).json();
  const base = `/projects/${project.id}`;
  await page.addInitScript(value => localStorage.setItem("token", value), token);
  await page.goto(`/dashboard/projects/${project.id}`);
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await page.getByRole("button", { name: "새 과제", exact: true }).click();
  await page.getByLabel("과제 제목", { exact: true }).fill("매주 운영 점검");
  await page.getByRole("combobox", { name: "담당자", exact: true }).selectOption(String(me.id));
  await page.getByLabel("마감일", { exact: true }).fill("2026-09-22");
  await page.getByLabel("반복 간격", { exact: true }).fill("7");
  await page.getByRole("button", { name: "체크 항목 추가" }).click();
  await page.getByLabel("체크리스트 1 내용").fill("오류 로그 검토");
  await page.getByLabel("과제 상태").selectOption("DONE");
  await page.getByRole("button", { name: "과제 저장", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("alert")).toContainText("체크리스트의 모든 항목");
  await expect(page.getByLabel("체크리스트 1 완료")).toBeEnabled();
  await page.getByLabel("과제 상태").selectOption("TODO");
  await page.getByRole("button", { name: "같은 내용으로 재시도", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.goto("/dashboard");
  await page.getByRole("button", { name: "내 작업함", exact: true }).click();
  await page.getByLabel("작업 기준일").fill("2026-09-22");
  await page.getByLabel("마감 필터").selectOption("today");
  await page.getByRole("link", { name: "매주 운영 점검", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("heading", { name: "실행 과제", exact: true })).toBeVisible();
  await page.getByLabel("과제 상태").selectOption("DONE");
  await page.getByRole("button", { name: "과제 저장", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("alert")).toContainText("체크리스트의 모든 항목");
  await page.getByLabel("체크리스트 1 완료").check();
  await page.getByRole("button", { name: "같은 내용으로 재시도", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const tasks = (await (await request.get(`${base}/tasks`, { headers })).json()).items;
  expect(tasks).toHaveLength(2);
  const next = tasks.find((task: { recurrence_parent_id: string | null }) => task.recurrence_parent_id);
  expect(next.due_date).toBe("2026-09-29");
  expect(next.checklist[0].done).toBe(false);
  await page.getByRole("button", { name: "현황", exact: true }).click();
  await page.getByLabel("현황 기준일").fill("2026-09-22");
  await expect(page.getByRole("region", { name: "프로젝트 현황", exact: true })).toContainText("완료율 50% · 1/2");
  await page.screenshot({ path: info.outputPath("execution-overview-desktop.png"), fullPage: true });
  // Navigation within the same project must react to the task link.
  await page.getByRole("region", { name: "임박 과제" }).getByRole("link", { name: "매주 운영 점검" }).click();
  await expect(page.getByRole("dialog")).toContainText("이전 회차를 완료해 생성된 반복 과제");
  await expect(page.getByLabel("마감일", { exact: true })).toHaveValue("2026-09-29");
  await page.keyboard.press("Escape");
  await page.goto("/dashboard");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "내 작업함", exact: true }).click();
  await page.getByLabel("작업 기준일").fill("2026-09-29");
  await page.getByLabel("마감 필터").selectOption("today");
  await expect(page.getByRole("link", { name: "매주 운영 점검", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("execution-my-work-mobile.png"), fullPage: true });
});

test("task deep link preserves an unrelated local draft", async ({ page, request }) => {
  const email = `draft-execution-${randomUUID()}@example.com`, password = "ExecutionValidation!42";
  await request.post("/auth/register", { data: { email, password } });
  const token = (await (await request.post("/auth/login", { form: { username: email, password } })).json()).access_token;
  const headers = { Authorization: `Bearer ${token}` };
  const project = await (await request.post("/projects", { headers, data: { name: "초안 보호" } })).json();
  const id = randomUUID();
  await request.post(`/projects/${project.id}/tasks`, { headers, data: { id, title: "링크 대상" } });
  await page.addInitScript(value => localStorage.setItem("token", value), token);
  await page.goto(`/dashboard/projects/${project.id}?view=tasks`);
  await page.getByRole("button", { name: "새 과제", exact: true }).click();
  await page.getByLabel("과제 제목", { exact: true }).fill("보존할 작성 중 내용");
  await page.keyboard.press("Escape");
  await page.goto(`/dashboard/projects/${project.id}?view=tasks&task=${id}`);
  await expect(page.getByText("다른 과제의 초안이 있습니다.", { exact: false })).toBeVisible();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "과제 초안 이어쓰기" }).click();
  await expect(page.getByLabel("과제 제목", { exact: true })).toHaveValue("보존할 작성 중 내용");
});
