import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";

test("knowledge to task, discussion, AI review and mobile workspace", async ({ page, request }, info) => {
  const email = `workspace-${Date.now()}@example.com`, password = "WorkspaceValidation!42";
  expect((await request.post("/auth/register", { data: { email, password, name: "작업 공간 검증" } })).status()).toBe(201);
  const token = (await (await request.post("/auth/login", { form: { username: email, password } })).json()).access_token;
  const headers = { Authorization: `Bearer ${token}` };
  const project = await (await request.post("/projects", { headers, data: { name: "제품 출시 작업 공간", description: "아이디어를 검토하고 실행하는 흐름" } })).json();
  await page.addInitScript(value => localStorage.setItem("token", value), token);
  await page.goto(`/dashboard/projects/${project.id}`);
  await page.getByRole("button", { name: "지식", exact: true }).click();
  await page.getByRole("button", { name: "북마크 저장", exact: false }).first().click();
  await expect(page.getByRole("button", { name: "북마크 해제", exact: false })).toBeVisible();
  await page.getByRole("button", { name: "실행 과제로 연결" }).first().click();
  await page.getByLabel("과제 제목", { exact: true }).fill("고객 인터뷰 세 명 진행");
  await page.getByLabel("완료 조건과 내용", { exact: true }).fill("의견을 정리해 팀과 공유한다.");
  await page.getByRole("button", { name: "과제 저장", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "AI 검토에 추가" }).first().click();
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await page.getByRole("button", { name: "고객 인터뷰 세 명 진행", exact: false }).click();
  await page.getByLabel("과제 상태").selectOption("DOING");
  await page.getByRole("button", { name: "과제 저장", exact: true }).click();
  await expect(page.getByRole("region", { name: "진행 중", exact: true })).toContainText("고객 인터뷰 세 명 진행");
  await page.screenshot({ path: info.outputPath("workspace-board.png"), fullPage: true });
  await page.getByRole("button", { name: "토론", exact: true }).click();
  await page.getByRole("button", { name: "새 토론", exact: true }).click();
  await page.getByLabel("토론 내용", { exact: true }).fill("인터뷰 질문부터 합의합시다.");
  await page.getByRole("button", { name: "토론 저장", exact: true }).click();
  await expect(page.getByText("인터뷰 질문부터 합의합시다.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "AI 검토 (1)", exact: true }).click();
  await page.getByRole("button", { name: "AI 제안 요청", exact: true }).click();
  await expect(page.getByText("검토 대기", { exact: true })).toBeVisible({ timeout: 15000 });
  await page.getByRole("button", { name: "검토 후 과제로 채택", exact: true }).click();
  await page.getByLabel("채택할 과제 제목").fill("AI에서 제안한 실험");
  await page.getByRole("button", { name: "과제 생성 확인", exact: true }).click();
  await expect(page.getByText("과제로 채택됨", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await expect(page.getByRole("button", { name: "AI에서 제안한 실험", exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("workspace-mobile.png"), fullPage: true });
  await page.reload();
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await expect(page.getByRole("region", { name: "실행 보드", exact: true })).toContainText("고객 인터뷰 세 명 진행");
});

test("draft reload and lost response recover, workspace download restores, templates and searches persist", async ({ page, request }, info) => {
  const email = `workspace-recovery-${Date.now()}@example.com`, password = "WorkspaceValidation!42";
  expect((await request.post("/auth/register", { data: { email, password, name: "복구 검증" } })).status()).toBe(201);
  const token = (await (await request.post("/auth/login", { form: { username: email, password } })).json()).access_token;
  const headers = { Authorization: `Bearer ${token}` };
  const project = await (await request.post("/projects", { headers, data: { name: "복구 가능한 작업 공간" } })).json();
  await page.addInitScript(value => localStorage.setItem("token", value), token);
  await page.goto(`/dashboard/projects/${project.id}`);
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await page.getByRole("button", { name: "새 과제", exact: true }).click();
  await page.getByLabel("과제 제목", { exact: true }).fill("새로고침에도 남는 과제");
  await page.getByLabel("완료 조건과 내용", { exact: true }).fill("원본 입력을 잃지 않는다.");
  await page.reload();
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await page.getByRole("button", { name: "과제 초안 이어쓰기" }).click();
  await expect(page.getByLabel("과제 제목", { exact: true })).toHaveValue("새로고침에도 남는 과제");
  let dropped = false;
  await page.route(`**/projects/${project.id}/tasks`, async route => {
    if (route.request().method() === "POST" && !dropped) { dropped = true; const response = await route.fetch(); expect(response.status()).toBe(201); await route.abort("failed"); }
    else await route.continue();
  });
  await page.getByRole("button", { name: "과제 저장", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("alert")).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await page.getByRole("button", { name: "과제 초안 이어쓰기" }).click();
  await expect(page.getByLabel("과제 제목", { exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "과제 저장", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect((await (await request.get(`/projects/${project.id}/tasks`, { headers })).json()).items).toHaveLength(1);
  await page.getByRole("button", { name: "토론", exact: true }).click();
  await page.getByRole("button", { name: "새 토론", exact: true }).click();
  await page.getByLabel("토론 내용", { exact: true }).fill("보존할 토론 초안");
  await page.reload();
  await page.getByRole("button", { name: "토론", exact: true }).click();
  await page.getByRole("button", { name: "토론 초안 이어쓰기" }).click();
  await expect(page.getByLabel("토론 내용", { exact: true })).toHaveValue("보존할 토론 초안");
  await page.getByRole("button", { name: "토론 저장", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "지식", exact: true }).click();
  await page.getByLabel("지식 검색어").fill("주제");
  await page.getByRole("button", { name: "검색", exact: true }).click();
  await page.getByRole("button", { name: "현재 검색 저장" }).click();
  await page.getByLabel("저장 이름", { exact: true }).fill("주제 찾아보기");
  await page.getByRole("button", { name: "이름으로 저장" }).click();
  await expect(page.getByRole("button", { name: "주제 찾아보기", exact: true })).toBeVisible();
  await page.getByText("작업 공간 백업", { exact: true }).click();
  await page.getByRole("button", { name: "내 템플릿으로 저장" }).click();
  await page.getByLabel("저장 이름", { exact: true }).fill("주간 회의 템플릿");
  await page.getByRole("button", { name: "이름으로 저장" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const downloading = page.waitForEvent("download");
  await page.getByRole("button", { name: "작업 공간 JSON 다운로드" }).click();
  const download = await downloading, backupPath = info.outputPath("workspace-v2.json");
  await download.saveAs(backupPath);
  const backup = JSON.parse(await fs.readFile(backupPath, "utf8"));
  expect(backup.schema_version).toBe(2); expect(backup.tasks).toHaveLength(1); expect(backup.discussions).toHaveLength(1);
  await page.goto("/dashboard");
  await expect(page.getByRole("button", { name: "주간 회의 템플릿 → 새 프로젝트", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "JSON 백업 가져오기" }).click();
  await page.getByLabel("백업 JSON 파일", { exact: true }).setInputFiles(backupPath);
  await expect(page.getByRole("dialog")).toContainText("과제 1개 · 토론 1개");
  await page.getByRole("button", { name: "새 프로젝트 생성 확인" }).click();
  await expect(page).toHaveURL(/\/dashboard\/projects\/\d+/);
  expect(page.url()).not.toContain(`/projects/${project.id}`);
  await page.getByRole("button", { name: "실행 보드", exact: true }).click();
  await expect(page.getByRole("region", { name: "실행 보드", exact: true })).toContainText("새로고침에도 남는 과제");
  await page.goto("/dashboard");
  await page.getByRole("button", { name: "주간 회의 템플릿 → 새 프로젝트", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard\/projects\/\d+/);
  await page.getByRole("button", { name: "토론", exact: true }).click();
  await expect(page.getByText("보존할 토론 초안", { exact: true })).toBeVisible();
});
